---
# Ansible tests.
# Ignore errors is set to 'true' in order to enable CI

- name: Verify
  hosts: all
  gather_facts: false
  ignore_errors: true

  tasks:
    - name: 'Test OK - 1'
      ansible.builtin.assert:
        that:
          - 1 == 1

    - name: 'Test OK - 2'
      ansible.builtin.assert:
        that:
          - 2 == 2 
