---
# This is an example playbook to execute Ansible tests.

- name: 'verify'
  hosts: all
  gather_facts: false
  ignore_errors: true

  tasks:
    - name: 'test simple'
      ansible.builtin.assert:
        that:
          - 1 == 1