---
# This is an example playbook to execute Ansible tests.

- name: 'Verify'
  hosts: all
  gather_facts: false
  tasks:
    - name: 'TEST: Example assertion'
      ansible.builtin.assert:
        that: true
