---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
platforms:
  - name: test
    image: python:slim
    pre_build_image: true
driver:
  name: docker
provisioner:
  name: ansible
  inventory:
    group_vars:
      all: {}
verifier:
  name: ansible
