---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
platforms:
  - name: test
    image: alpine:latest
    pre_build_image: true
driver:
  name: docker
provisioner:
  name: ansible
verifier:
  name: ansible
