---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
platforms:
  - name: test
    image: python:slim
    pre_build_image: true
driver:
  name: docker
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    group_vars:
      all: {}
verifier:
  name: ansible
  env:
    FOO: bar
