---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
driver:
  name: delegated
rovisioner:
  name: ansible
verifier:
  name: ansible
