name: 'Check Branch Name'

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: "job to test branch name"
    steps:
      - uses: calavia-org/check-branch-naming-action@v1.0.2
        with:
            allowed_branch_re: feat