name: Test collection

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - collections/ansible_collections/calaviaorg/setup/playbooks/**
      - collections/ansible_collections/calaviaorg/setup/plugins/**
      - collections/ansible_collections/calaviaorg/setup/roles/**
      - tests/**
      - extensions/molecule/**
      - galaxy.yml
      - requirements.yml
      - tox-ini
  push:
    paths:
      - collections/ansible_collections/calaviaorg/setup/playbooks/**
      - collections/ansible_collections/calaviaorg/setup/plugins/**
      - collections/ansible_collections/calaviaorg/setup/roles/**
      - tests/**
      - extensions/molecule/**
      - galaxy.yml
      - requirements.yml
      - tox-ini
jobs:
  tox-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tox-ansible, includes tox
        run: python3 -m pip install tox-ansible

      - name: Generate unit-tests matrix
        id: unit-matrix
        run: |
          python3 -m tox --ansible --gh-matrix --matrix-scope unit --conf tox-ansible.ini

      - name: Generate integration-tests matrix
        id: integration-matrix
        run: |
          python3 -m tox --ansible --gh-matrix --matrix-scope integration --conf tox-ansible.ini

    outputs:
      unitEnvList: ${{ steps.unit-matrix.outputs.envlist }}
      integrationEnvList: ${{ steps.integration-matrix.outputs.envlist }}

  unit_test:
    needs: tox-matrix
    strategy:
      fail-fast: false
      matrix:
        entry: ${{ fromJson(needs.tox-matrix.outputs.unitEnvList) }}
    name: ${{ matrix.entry.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.entry.python }}

      - name: Install tox-ansible, includes tox
        run: python3 -m pip install tox-ansible

      - name: Run tox test
        run: >-
          python3 -m tox
          --ansible
          -e ${{ matrix.entry.name }}
          --conf tox-ansible.ini
          --
          --show-capture=all
          --cov=unit
          --cov-report=xml
          --junit-xml=test/reports/unit-${{ matrix.entry.name }}.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test/reports/unit-*.xml


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}          

  integration_test:
    needs: tox-matrix
    strategy:
      fail-fast: false
      matrix:
        entry: ${{ fromJson(needs.tox-matrix.outputs.integrationEnvList) }}
    name: ${{ matrix.entry.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.entry.python }}
      
      - name: Install tox-ansible, includes tox
        run: python3 -m pip install tox-ansible
      
      - name: Run tox test
        run: >-
          python3 -m tox
          --ansible
          -e ${{ matrix.entry.name }}
          --conf tox-ansible.ini
          --
          --show-capture=all
          --junit-xml=test/reports/integration-${{ matrix.entry.name }}.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test/reports/integration-*.xml

  test_passed:
    needs: [unit_test, integration_test]
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.unit_test.result }}',
          '${{ needs.integration_test.result }}'
          ]) == {'success'}"
